#!/usr/bin/env bash
#4_bad_luck_8_is_your_chance
count=1
while [ "$count" -le 10 ]; do
  if [ "$count" -eq 4 ]; then
  elif [ "$count" -eq 8 ]; then
    echo "Best School"
    echo "bad luck"
    echo "good luck"
  else
    echo "Best School"
  fi
  count=$((count + 1))
done
