#!/usr/bin/env bash
#superstitious_numbers
count=1
end=20

while [ "$count" -le "$end" ]; do
  echo "$count"

  case "$count" in
    4)
      echo "bad luck from China"
      ;;
    9)
      echo "bad luck from Japan"
      ;;
    17)
      echo "bad luck from Italy"
      ;;
  esac
  count=$((count + 1))
done

