#!/usr/bin/env bash
#process_and_pid_file
PID_FILE="/var/run/myscript.pid"
echo $$ > "$PID_FILE"
trap 'echo "I hate the kill command"; rm -f "$PID_FILE"; exit 0' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f "$PID_FILE"; exit 0' SIGQUIT
while true; do
    echo "To infinity and beyond"
    sleep 2
done
