#!/usr/bin/env bash
#to_infinity_and_beyond
STOP_FILE="/tmp/stop_infinity"

while true; do
    if [[ -f "$STOP_FILE" ]]; then
        echo "Terminated"
        rm -f "$STOP_FILE"
        exit 0
    fi
    echo "To infinity and beyond"
    sleep 2
done


